name: hondooye_logger
description: A useful logger.
version: 0.0.2
repository: https://github.com/Doohyeon-Kim/hondooye-logger

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  logger: ^1.1.0
  http: ^0.13.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter: